name: Deployment workflow
on: push
jobs:
  test:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test

  lint:
    needs: test
    name: Lint tests
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  build:
    needs: [test, lint]
    name: Build the code
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
  
  